[package]
name = "snake"
version = "0.1.0"
authors = ["magonzalezoc@gmail.com"]
edition = "2021"

[dependencies]
parking_lot = "0.11"
bevy = "0.11.3"
rand = {version="0.7.3", features=["wasm-bindgen"]}
getrandom = { version = "0.2", features = ["js"] }
